noticias:
    path:     /
    defaults: { _controller: "ColeBundle:Noticias:noticias" }

noticias_consultar:
    path:     /consultar
    defaults: { _controller: "ColeBundle:Noticias:index" }

noticias_imagen:
    path:     /imagen
    defaults: { _controller: "ColeBundle:Noticias:imagen" }
    options:
        expose: true

noticias_galeria:
    path:     /galeria
    defaults: { _controller: "ColeBundle:Noticias:galeria" }
    options:
        expose: true

imagen_create:
    path:     /imagen_create
    defaults: { _controller: "ColeBundle:Noticias:imagen_create" }
    options:
        expose: true

imagen_delete:
    path:     /imagen_delete
    defaults: { _controller: "ColeBundle:Noticias:imagen_delete" }
    options:
        expose: true

galeria_create:
    path:     /galeria_create
    defaults: { _controller: "ColeBundle:Noticias:galeria_create" }
    options:
        expose: true

galeria_editar:
    path:     /galeria_editar
    defaults: { _controller: "ColeBundle:Noticias:galeria_editar" }
    options:
        expose: true

mostrar_galeria_editada:
    path:     /mostrar_galeria_editada
    defaults: { _controller: "ColeBundle:Noticias:mostrar_galeria_editada" }
    options:
        expose: true

galerias_delete:
    path:     /galerias_delete
    defaults: { _controller: "ColeBundle:Noticias:galerias_delete" }
    options:
        expose: true

renombrar_galeria:
    path:     /renombrar_galeria
    defaults: { _controller: "ColeBundle:Noticias:renombrar_galeria" }
    options:
        expose: true

recuperar_galeria:
    path:     /recuperar_galeria
    defaults: { _controller: "ColeBundle:Noticias:recuperar_galeria" }
    options:
        expose: true

contador_noticias:
    path:     /contador_noticias
    defaults: { _controller: "ColeBundle:Noticias:contadorNoticias" }
    options:
        expose: true

noticias_show:
    path:     /{id}/show
    defaults: { _controller: "ColeBundle:Noticias:show" }

noticia:
    path:     /{id}
    defaults: {_controller: "ColeBundle:Noticias:noticia"}

noticias_new:
    path:     /new/
    defaults: { _controller: "ColeBundle:Noticias:new" }

noticias_create:
    path:     /create/
    defaults: { _controller: "ColeBundle:Noticias:create" }
    requirements: { _method: post }
    options:
        expose: true

noticias_edit:
    path:     /{id}/edit
    defaults: { _controller: "ColeBundle:Noticias:edit" }
    options:
        expose: true

noticias_update:
    path:     /{id}/update
    defaults: { _controller: "ColeBundle:Noticias:update" }
    requirements: { _method: post|put }

noticias_delete:
    path:     /{id}/delete
    defaults: { _controller: "ColeBundle:Noticias:delete" }
    requirements: { _method: post|delete }
    options:
        expose: true


