intranet_alumno:
    path:     /
    defaults: { _controller: IntranetBundle:Alumno:index}

intranet_alumno_perfil:
    path:     /perfil
    defaults: { _controller: IntranetBundle:Alumno:perfil}

intranet_alumno_curso:
    path:     /curso
    defaults: { _controller: IntranetBundle:Alumno:curso}

horario_alumno:
    pattern:  /horario
    defaults: { _controller: "IntranetBundle:Alumno:Horario"}
    options:
      expose: true

horario_alumno_pdf:
    pattern:  /horarioPdf
    defaults: { _controller: "IntranetBundle:Alumno:HorarioPdf", _format: pdf}
    options:
      expose: true

intranet_alumno_seguimientos:
    path:     /seguimiento
    defaults: { _controller: IntranetBundle:Alumno:seguimientos}
    options:
        expose: true

cargar_seguimientos_alumno:
    path:     /cargar_seguimientos/{iden}
    defaults: { _controller: IntranetBundle:Alumno:CargarSeguimientos}
    options:
        expose: true

cargar_nuevos_seguimientos_alumno:
    path:     /cargar_nuevos_seguimientos/{fecha}
    defaults: { _controller: IntranetBundle:Alumno:CargarNuevosSeguimientos}
    options:
        expose: true

nuevos_seguimientos_alumno:
    path:     /nuevos_seguimientos
    defaults: { _controller: IntranetBundle:Alumno:comprobarSeguimientosNuevos}
    options:
        expose: true

intranet_alumno_seguimiento:
    path:     /seguimiento/{num}
    defaults: { _controller: IntranetBundle:Alumno:seguimiento}

intranet_alumno_calificaciones:
    path:     /calificaciones
    defaults: { _controller: IntranetBundle:Alumno:calificaciones}
    options:
        expose: true

calificacionesTareasAlumno:
    path:     /calificacionesTareasAlumno/{asig}
    defaults: { _controller: IntranetBundle:Alumno:calificacionesTareasAlumno}
    options:
        expose: true

intranet_alumno_tutorias:
    path:     /tutorias
    defaults: { _controller: IntranetBundle:Alumno:tutorias}

intranet_alumno_seguimiento_tutoria:
    path:     /tutoria/{num}
    defaults: { _controller: IntranetBundle:Alumno:seguimientoTutoria}

nuevos_seguimiento_tutorias_alumno:
    path:     /nuevos_seguimiento_tutorias
    defaults: { _controller: IntranetBundle:Alumno:comprobarSeguimientosTutoriasNuevos}
    options:
        expose: true

cargar_nuevos_seguimientos_tutoria_alumno:
    path:     /cargar_nuevos_seguimientos_tutoria/{fecha}
    defaults: { _controller: IntranetBundle:Alumno:CargarNuevosSeguimientosTutoria}
    options:
        expose: true

cargar_seguimientos_tutoria_alumno:
    path:     /cargar_seguimientos_tutoria/{iden}/{tipo}
    defaults: { _controller: IntranetBundle:Alumno:CargarSeguimientosTutoria}
    options:
        expose: true

info_tutoria_alumno:
    path:     /info_tutoria/{num}
    defaults: { _controller: IntranetBundle:Alumno:InfoTutoria}
    options:
        expose: true

confirmar_tutoria:
    path:     /confirmar_tutoria/{num}
    defaults: { _controller: IntranetBundle:Alumno:ConfirmarTutoria}
    options:
        expose: true

cancelar_tutoria:
    path:     /cancelar_tutoria/{num}
    defaults: { _controller: IntranetBundle:Alumno:CancelarTutoria}
    options:
        expose: true
intranet_alumno_noticias:
    path:     /noticias
    defaults: { _controller: IntranetBundle:Alumno:noticias}

intranet_alumno_noticia:
    path:     /noticia/{num}
    defaults: { _controller: IntranetBundle:Alumno:noticia}

nuevas_noticias_alumno:
    path:     /nuevas_noticias
    defaults: { _controller: IntranetBundle:Alumno:comprobarNoticiasNuevas}
    options:
        expose: true


