intranet_profesor:
    path:     /
    defaults: { _controller: IntranetBundle:Profesor:index}

intranet_profesor_cursos:
    path:     /cursos
    defaults: { _controller: IntranetBundle:Profesor:cursos}

datos_alumnos_grupo:
    path:     /datos_alumnos_grupo/{id}
    defaults: { _controller: IntranetBundle:Profesor:datosAlumnosGrupo}
    options:
        expose: true

info_alumno:
    path:     /info_alumno/{id}
    defaults: { _controller: IntranetBundle:Profesor:InfoAlumno}
    options:
        expose: true

info_profesor:
    path:     /info_profesor/{id}
    defaults: { _controller: IntranetBundle:Profesor:InfoProfesor}
    options:
        expose: true

asignaturasGrupo_profesor:
    path:     /asignaturas/profesor/{id}
    defaults: { _controller: IntranetBundle:Profesor:AsignaturasGrupoProfesor}
    options:
        expose: true

horario_profesor:
    pattern:  /horario
    defaults: { _controller: "IntranetBundle:Profesor:Horario"}
    options:
      expose: true

#horario_alumno_pdf:
#    pattern:  /horarioPdf
#    defaults: { _controller: "IntranetBundle:Alumno:HorarioPdf", _format: pdf}
#    options:
#      expose: true

intranet_profesor_seguimientos:
    path:     /seguimiento
    defaults: { _controller: IntranetBundle:Profesor:seguimientos}
    options:
        expose: true

intranet_profesor_seguimiento:
    path:     /{num}/seguimiento/
    defaults: { _controller: IntranetBundle:Profesor:seguimiento}

cargar_seguimientos_profesor:
    path:     /cargar_seguimientos/{id}
    defaults: { _controller: IntranetBundle:Profesor:CargarSeguimientos}
    options:
        expose: true

cargar_nuevos_seguimientos_profesor:
    path:     /cargar_nuevos_seguimientos/{fecha}
    defaults: { _controller: IntranetBundle:Profesor:CargarNuevosSeguimientos}
    options:
        expose: true

nuevos_seguimientos_profesor:
    path:     /{id}/nuevos_seguimientos
    defaults: { _controller: IntranetBundle:Profesor:comprobarSeguimientosNuevos}
    options:
        expose: true

AlumnosGrupoAsignatura:
    path:     /GrupoAsignatura/{id}/{asig}
    defaults: { _controller: IntranetBundle:Profesor:AlumnosGrupoAsignatura}
    options:
        expose: true

AlumnosGrupo:
    path:     /GrupoAsignatura/{id}
    defaults: { _controller: IntranetBundle:Profesor:AlumnosGrupo}
    options:
        expose: true

intranet_profesor_reservas:
    path:     /reservas
    defaults: { _controller: IntranetBundle:Profesor:reservas}

intranet_profesor_reservar_create:
    path:     /reservar/create
    defaults: { _controller: "IntranetBundle:Profesor:createReserva" }
    requirements: { _method: post }

comprobar_reservas_profesor:
    path:     /comprobar_reservas
    defaults: { _controller: "IntranetBundle:Profesor:ComprobarReservas" }
    options:
        expose: true

intranet_profesor_reservar_instalacion:
    path:     /reservar/instalación
    defaults: { _controller: IntranetBundle:Profesor:reservarInstalacion}
    options:
        expose: true

intranet_profesor_reservar_equipamiento:
    path:     /reservar/equipamiento
    defaults: { _controller: IntranetBundle:Profesor:reservarEquipamiento}
    options:
        expose: true

reserva_eliminar:
    path:     /reserva/{id}/eliminar
    defaults: { _controller: "IntranetBundle:Profesor:eliminarReserva" }
    options:
        expose: true

intranet_profesor_reserva_delete:
    path:     /reserva/{id}/delete
    defaults: { _controller: "IntranetBundle:Profesor:deleteReserva" }
    requirements: { _method: post|delete }
    options:
        expose: true

intranet_profesor_tutorias:
    path:     /tutorias
    defaults: { _controller: IntranetBundle:Profesor:tutorias}
    options:
        expose: true

intranet_profesor_seguimiento_tutoria:
    path:     /{num}/tutoria/
    defaults: { _controller: IntranetBundle:Profesor:seguimientoTutoria}
    options:
        expose: true

cargar_seguimientos_tutoria_profesor:
    path:     /cargar_seguimientos_tutoria/{id}
    defaults: { _controller: IntranetBundle:Profesor:CargarSeguimientosTutoria}
    options:
        expose: true

cargar_nuevos_seguimientos_tutoria_profesor:
    path:     /cargar_nuevos_seguimientos_tutoria/{fecha}
    defaults: { _controller: IntranetBundle:Profesor:CargarNuevosSeguimientosTutoria}
    options:
        expose: true

nuevas_tutorias_profesor:
    path:     /{id}/nuevas_tutorias
    defaults: { _controller: IntranetBundle:Profesor:comprobarTutoriasNuevas}
    options:
        expose: true

intranet_profesor_noticias:
    path:     /noticias
    defaults: { _controller: IntranetBundle:Profesor:noticias}
    options:
        expose: true

intranet_profesor_noticia:
    path:     /noticia/{num}
    defaults: { _controller: IntranetBundle:Profesor:noticia}

nuevas_noticias_profesor:
    path:     /{id}/nuevas_noticias
    defaults: { _controller: IntranetBundle:Profesor:comprobarNoticiasNuevas}
    options:
        expose: true




