intranet_profesor:
    path:     /
    defaults: { _controller: IntranetBundle:Profesor:index}

intranet_profesor_cursos:
    path:     /cursos
    defaults: { _controller: IntranetBundle:Profesor:cursos}

horario_profesor:
    pattern:  /horario
    defaults: { _controller: "IntranetBundle:Profesor:Horario"}
    options:
      expose: true

#horario_alumno_pdf:
#    pattern:  /horarioPdf
#    defaults: { _controller: "IntranetBundle:Alumno:HorarioPdf", _format: pdf}
#    options:
#      expose: true

intranet_profesor_seguimientos:
    path:     /seguimiento
    defaults: { _controller: IntranetBundle:Profesor:seguimientos}
    options:
        expose: true

intranet_profesor_seguimiento:
    path:     /{num}/seguimiento/
    defaults: { _controller: IntranetBundle:Profesor:seguimiento}

cargar_seguimientos_profesor:
    path:     /cargar_seguimientos/{id}
    defaults: { _controller: IntranetBundle:Profesor:CargarSeguimientos}
    options:
        expose: true

intranet_profesor_noticias:
    path:     /noticias
    defaults: { _controller: IntranetBundle:Profesor:noticias}
    options:
        expose: true

intranet_profesor_noticia:
    path:     /noticia/{num}
    defaults: { _controller: IntranetBundle:Profesor:noticia}

nuevas_noticias_profesor:
    path:     /{id}/nuevas_noticias
    defaults: { _controller: IntranetBundle:Profesor:comprobarNoticiasNuevas}
    options:
        expose: true

nuevos_seguimientos_profesor:
    path:     /{id}/nuevos_seguimientos
    defaults: { _controller: IntranetBundle:Profesor:comprobarSeguimientosNuevos}
    options:
        expose: true

datos_alumnos_grupo:
    path:     /datos_alumnos_grupo/{id}
    defaults: { _controller: IntranetBundle:Profesor:datosAlumnosGrupo}
    options:
        expose: true

info_alumno:
    path:     /info_alumno/{id}
    defaults: { _controller: IntranetBundle:Profesor:InfoAlumno}
    options:
        expose: true

info_profesor:
    path:     /info_profesor/{id}
    defaults: { _controller: IntranetBundle:Profesor:InfoProfesor}
    options:
        expose: true

asignaturasGrupo_profesor:
    path:     /asignaturas/profesor/{id}
    defaults: { _controller: IntranetBundle:Profesor:AsignaturasGrupoProfesor}
    options:
        expose: true

AlumnosGrupoAsignatura:
    path:     /GrupoAsignatura/{id}/{asig}
    defaults: { _controller: IntranetBundle:Profesor:AlumnosGrupoAsignatura}
    options:
        expose: true

AlumnosGrupo:
    path:     /GrupoAsignatura/{id}
    defaults: { _controller: IntranetBundle:Profesor:AlumnosGrupo}
    options:
        expose: true
