<?php

namespace Cole\ColeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CentroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentroRepository extends EntityRepository
{
}
