<?php

namespace Cole\ColeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoticiasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiasRepository extends EntityRepository
{
	public function findRecientes()
	{
		$em = $this->getEntityManager();
		$consulta = $em->createQuery('SELECT n FROM ColeBundle:Noticias n WHERE n.categoria = :categoria ORDER BY n.fecha DESC');
		$consulta->setMaxResults(4);
		$consulta->setParameter('categoria', 'general');
		return $consulta->getResult();
	}

	public function findNuevasNoticias($ultimo_acceso, $categoria)
	{
	return $this->getEntityManager()->createQuery(
		'SELECT n FROM ColeBundle:Noticias n WHERE n.categoria=:categoria AND n.fecha>:ultimo_acceso ORDER BY n.fecha DESC')
		->setParameters(array(
			'categoria' => $categoria,
			'ultimo_acceso'=>$ultimo_acceso))
		->getResult();
	}


	

}
