alumno:
    path:     /
    defaults: { _controller: "BackendBundle:Alumno:index" }

alumno_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Alumno:show" }

alumno_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Alumno:new" }

alumno_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Alumno:create" }
    requirements: { _method: post }
    options:
        expose: true

alumno_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Alumno:edit" }
    options:
        expose: true

alumno_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Alumno:update" }
    requirements: { _method: post|put }
    options:
        expose: true

alumno_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Alumno:delete" }
    requirements: { _method: post|delete }

alumno_search:
    path:     /alumno/search
    defaults: { _controller: "BackendBundle:Alumno:search" }
    options:
        expose: true

alumno_listaCursos:
    path:     /alumno/listaCursos
    defaults: { _controller: "BackendBundle:Curso:ListaCursos" }
    options:
        expose: true

comprobar_alumno:
    path:     /comprobaralumno
    defaults: { _controller: "BackendBundle:Alumno:ComprobarAlumno" }
    options:
        expose: true

alumnos_por_curso:
    path:     /alumnos_por_curso/{id}
    defaults: { _controller: "BackendBundle:Alumno:AlumnosPorCurso" }
    options:
        expose: true

asignar_responsable:
    path:     /asignar_responsable
    defaults: { _controller: "BackendBundle:Alumno:AsignarResponsable" }
    options:
        expose: true

eliminar_responsable:
    path:     /eliminar_responsable
    defaults: { _controller: "BackendBundle:Alumno:EliminarResponsable" }
    options:
        expose: true

alumnos_asignados_curso:
    path:     /alumnos_asignados_curso
    defaults: { _controller: "BackendBundle:Alumno:AlumnosAsignadosCurso" }
    options:
        expose: true

alumnos_asignados_grupo:
    path:     /alumnos_asignados_grupo
    defaults: { _controller: "BackendBundle:Alumno:AlumnosAsignadosGrupo" }
    options:
        expose: true

search_old:
    path:     /alumno/old/search
    defaults: { _controller: "BackendBundle:Alumno:SearchOld" }
    options:
        expose: true

search_multiple:
    path:     /alumno/multiple/search
    defaults: { _controller: "BackendBundle:Alumno:SearchMultiple" }
    options:
        expose: true

datos_alumno:
    path:     /datos_alumno/{id}
    defaults: { _controller: "BackendBundle:Alumno:DatosAlumno" }
    options:
        expose: true

antiguos_alumnos_por_curso:
    path:     /antiguos_alumnos_por_curso/{id}
    defaults: { _controller: "BackendBundle:Alumno:AntiguosAlumnosPorCurso" }
    options:
        expose: true

alumno_old_edit:
    path:     /{id}/old_edit
    defaults: { _controller: "BackendBundle:Alumno:OldEdit" }
    options:
        expose: true

antiguo_alumno_update:
    path:     /{id}/old_update
    defaults: { _controller: "BackendBundle:Alumno:OldUpdate" }
    requirements: { _method: post|put }
    options:
        expose: true

multiple_alumno_update:
    path:     /{id}/multiple_update
    defaults: { _controller: "BackendBundle:Alumno:MultipleUpdate" }
    requirements: { _method: post|put }
    options:
        expose: true