asignatura:
    path:     /
    defaults: { _controller: "BackendBundle:Asignatura:index" }
    options:
        expose: true

asignatura_show:
    path:     /show
    defaults: { _controller: "BackendBundle:Asignatura:show" }

asignatura_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Asignatura:new" }
    options:
        expose: true

asignatura_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Asignatura:create" }
    requirements: { _method: post }

asignatura_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Asignatura:edit" }
    options:
        expose: true

asignatura_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Asignatura:update" }
    requirements: { _method: post|put }

asignatura_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Asignatura:delete" }
    requirements: { _method: post|delete }
    options:
        expose: true

asignaturas_cursos:
    path:     /asignaturas_cursos
    defaults: { _controller: "BackendBundle:Asignatura:asignaturasCursos" }
    options:
        expose: true

asignaturas_curso_new:
    path:     /asignaturas_curso/{id}/new
    defaults: { _controller: "BackendBundle:Asignatura:AsignaturasCursoNew" }
    options:
        expose: true

comprobar_asignaturas:
    path:     /comprobar_asignaturas
    defaults: { _controller: "BackendBundle:Asignatura:ComprobarAsignaturas" }
    options:
        expose: true

asignar_asignaturas_curso:
    path:     /asignar_asignaturas_curso
    defaults: { _controller: "BackendBundle:Asignatura:AsignarAsignaturasCurso" }
    options:
        expose: true

eliminar_asignaciones_asignaturas:
    path:     /eliminar_asignaciones_asignaturas
    defaults: { _controller: "BackendBundle:Asignatura:EliminarAsignacionesAsignaturas" }
    options:
        expose: true

eliminar_todas_asignaciones_asignaturas:
    path:     /eliminar_todas_asignaciones_asignaturas
    defaults: { _controller: "BackendBundle:Asignatura:EliminarTodasAsignacionesAsignaturas" }
    options:
        expose: true

datos_asignatura:
    path:     /datos_asignatura/{id}/{id_grupo}
    defaults: { _controller: "BackendBundle:Asignatura:DatosAsignatura" }
    options:
        expose: true

show_optativas:
    path:     /show_optativas
    defaults: { _controller: "BackendBundle:Asignatura:showOptativas" }
    options:
        expose: true

asignar_optativa:
    path:     /asignar_optativa
    defaults: { _controller: "BackendBundle:Asignatura:AsignarOptativa" }
    options:
        expose: true