curso:
    path:     /
    defaults: { _controller: "BackendBundle:Curso:index" }
    options:
        expose: true

curso_show:
    path:     /show
    defaults: { _controller: "BackendBundle:Curso:show" }
    options:
        expose: true
        
curso_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Curso:new" }
    options:
        expose: true
curso_list:
    path:     /list
    defaults: { _controller: "BackendBundle:Curso:listaCursos" }
    options:
        expose: true
        
curso_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Curso:create" }
    requirements: { _method: post }

curso_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Curso:edit" }
    options:
        expose: true

curso_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Curso:update" }
    requirements: { _method: post|put }

curso_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Curso:delete" }
    requirements: { _method: post|delete }
    options:
        expose: true

Asignar_Ngrupos:
    path:     /Asignar_Ngrupos
    defaults: { _controller: "BackendBundle:Curso:AsignarNumeroGrupos" }
    options:
        expose: true

Listar_cursos:
    path:     /Listar_Cursos
    defaults: { _controller: "BackendBundle:Curso:ListarCursos" }
    options:
        expose: true

ordenar_cursos:
    path:     /Ordenar_Cursos
    defaults: { _controller: "BackendBundle:Curso:OrdenarCursos" }
    options:
        expose: true

ratio_cursos:
    path:     /Ratio_cursos
    defaults: { _controller: "BackendBundle:Curso:RatioCursos" }
    options:
        expose: true

asignar_ratio:
    path:     /Asignar_ratio
    defaults: { _controller: "BackendBundle:Curso:AsignarRatio" }
    requirements: { _method: post }
    options:
        expose: true