grupo:
    path:     /
    defaults: { _controller: "BackendBundle:Grupo:index" }

grupo_show:
    path:     /show
    defaults: { _controller: "BackendBundle:Grupo:show" }
    options:
        expose: true

grupo_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Grupo:new" }

grupo_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Grupo:create" }
    requirements: { _method: post }

grupo_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Grupo:edit" }

grupo_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Grupo:update" }
    requirements: { _method: post|put }

grupo_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Grupo:delete" }
    requirements: { _method: post|delete }

asignar_aula:
    path:     /asignar_aula
    defaults: { _controller: "BackendBundle:Grupo:AsignarAula" }
    options:
        expose: true

vaciar_aulas:
    path:     /vaciar_aulas
    defaults: { _controller: "BackendBundle:Grupo:VaciarAulas" }
    options:
        expose: true

asignar_grupo:
    path:     /Asignar_grupo
    defaults: { _controller: "BackendBundle:Grupo:AsignarGrupo" }
    options:
        expose: true

curso_asignar_grupo:
    path:     /{curso}/asignar_grupo
    defaults: { _controller: "BackendBundle:Grupo:CursoAsignarGrupo" }
    options:
        expose: true

asignar_grupo_update:
    path:     /asignar_grupo_update
    defaults: { _controller: "BackendBundle:Grupo:AsignarGrupoUpdate" }
    options:
        expose: true

tutor_grupo:
    path:     /tutor_grupo
    defaults: { _controller: "BackendBundle:Grupo:TutorGrupo" }
    options:
        expose: true

asignar_tutor_grupo:
    path:     /asignar_tutor_grupo
    defaults: { _controller: "BackendBundle:Grupo:AsignarTutorGrupo" }
    options:
        expose: true

asignar_horario_show:
    path:     /asignar_horario_show
    defaults: { _controller: "BackendBundle:Grupo:AsignarHorarioGrupoShow" }
    options:
        expose: true

asignar_horario_new:
    path:     /asignar_horario/{id}/new
    defaults: { _controller: "BackendBundle:Grupo:AsignarHorarioGrupoNew" }
    options:
        expose: true

asignar_horario_grupo:
    path:     /asignar_horario_grupo
    defaults: { _controller: "BackendBundle:Grupo:AsignarHorarioGrupo" }
    options:
        expose: true

eliminar_horario_grupo:
    path:     /eliminar_horario_grupo
    defaults: { _controller: "BackendBundle:Grupo:EliminarHorarioGrupo" }
    options:
        expose: true

eliminar_todos_horarios_grupos:
    path:     /eliminar_todos_horarios_grupos
    defaults: { _controller: "BackendBundle:Grupo:EliminarTodosHorariosGrupo" }
    options:
        expose: true

horario_grupo:
    pattern:  /{id}/horario
    defaults: { _controller: "BackendBundle:Grupo:HorarioDelGrupo"}
    options:
      expose: true

horario_grupo:
    pattern:  /{id}/horario
    defaults: { _controller: "BackendBundle:Grupo:HorarioDelGrupo"}
    options:
      expose: true

horario_grupo_pdf:
    pattern:  /{id}/horarioPdf
    defaults: { _controller: "BackendBundle:Grupo:HorarioDelGrupoPdf", _format: pdf}
    options:
      expose: true

horarios_grupos_pdf:
    pattern:  /horarios_gruposPdf
    defaults: { _controller: "BackendBundle:Grupo:HorariosGruposPdf", _format: pdf}
    options:
      expose: true

generar_horarios_pdf:
    path:     /generar_horarios_pdf/{id}
    defaults: { _controller: "BackendBundle:Grupo:GenerarHorariosPdf" }
    options:
        expose: true