grupo:
    path:     /
    defaults: { _controller: "BackendBundle:Grupo:index" }

grupo_show:
    path:     /show
    defaults: { _controller: "BackendBundle:Grupo:show" }
    options:
        expose: true

grupo_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Grupo:new" }

grupo_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Grupo:create" }
    requirements: { _method: post }

grupo_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Grupo:edit" }

grupo_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Grupo:update" }
    requirements: { _method: post|put }

grupo_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Grupo:delete" }
    requirements: { _method: post|delete }

asignar_aula:
    path:     /asignar_aula
    defaults: { _controller: "BackendBundle:Grupo:AsignarAula" }
    options:
        expose: true

vaciar_aulas:
    path:     /vaciar_aulas
    defaults: { _controller: "BackendBundle:Grupo:VaciarAulas" }
    options:
        expose: true

asignar_grupo:
    path:     /Asignar_grupo
    defaults: { _controller: "BackendBundle:Grupo:AsignarGrupo" }
    options:
        expose: true

curso_asignar_grupo:
    path:     /{curso}/asignar_grupo
    defaults: { _controller: "BackendBundle:Grupo:CursoAsignarGrupo" }
    options:
        expose: true

asignar_grupo_update:
    path:     /asignar_grupo_update
    defaults: { _controller: "BackendBundle:Grupo:AsignarGrupoUpdate" }
    options:
        expose: true
