imparte:
    path:     /
    defaults: { _controller: "BackendBundle:Imparte:index" }

imparte_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Imparte:show" }

imparte_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Imparte:new" }

imparte_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Imparte:create" }
    requirements: { _method: post }

imparte_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Imparte:edit" }

imparte_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Imparte:update" }
    requirements: { _method: post|put }

imparte_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Imparte:delete" }
    requirements: { _method: post|delete }

datos_imparte:
    path:     /datos_imparte
    defaults: { _controller: "BackendBundle:Imparte:DatosImparte" }
    options:
        expose: true

asignar_grupo_profesores_show:
    path:     /asignar_grupo_profesores_show
    defaults: { _controller: "BackendBundle:Imparte:AsignarGrupoProfesoresShow" }
    options:
        expose: true

asignar_grupo_profesores_new:
    path:     /asignar_grupo_profesores/{id}/new
    defaults: { _controller: "BackendBundle:Imparte:AsignarGrupoProfesoresNew" }
    options:
        expose: true

asignar_grupo_profesores:
    path:     /asignar_grupo_profesores
    defaults: { _controller: "BackendBundle:Imparte:AsignarGrupoProfesores" }
    options:
        expose: true

eliminar_asignaciones_grupo:
    path:     /eliminar_asignaciones_grupo
    defaults: { _controller: "BackendBundle:Imparte:EliminarAsignacionesGrupo" }
    options:
        expose: true

eliminar_todas_asignaciones_grupos:
    path:     /eliminar_todas_asignaciones_grupos
    defaults: { _controller: "BackendBundle:Imparte:EliminarTodasAsignacionesGrupos" }
    options:
        expose: true

comprobar_asignaciones_profesores:
    path:     /comprobar_asignaciones_profesores
    defaults: { _controller: "BackendBundle:Imparte:ComprobarAsignacionesProfesores" }
    options:
        expose: true

obtener_modulos_ocupados:    
    path:     /obtener_modulos_ocupados
    defaults: { _controller: "BackendBundle:Imparte:ObtenerModulosOcupados" }
    options:
        expose: true

comprobar_horas_profesor:
    path:     /comprobar_horas_profesor
    defaults: { _controller: "BackendBundle:Imparte:ComprobarHorasProfesor" }
    options:
        expose: true