profesor:
    path:     /
    defaults: { _controller: "BackendBundle:Profesor:index" }

profesor_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Profesor:show" }

profesor_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Profesor:new" }
    options:
        expose: true

profesor_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Profesor:create" }
    requirements: { _method: post }
    options:
        expose: true

profesor_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Profesor:edit" }
    options:
        expose: true

profesor_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Profesor:update" }
    requirements: { _method: post|put|get }
    options:
        expose: true

profesor_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Profesor:delete" }
    requirements: { _method: post|delete }

profesor_search:
    path:     /profesor/search
    defaults: { _controller: "BackendBundle:Profesor:search" }
    options:
        expose: true

comprobar_profesor:
    path:     /comprobarprofesor
    defaults: { _controller: "BackendBundle:Profesor:ComprobarProfesor" }
    options:
        expose: true

comprobar_dni_profesor:
    path:     /comprobar_dni_profesor
    defaults: { _controller: "BackendBundle:Profesor:ComprobarDniProfesor" }
    options:
        expose: true

comprobar_dni_profesor_editado:
    path:     /comprobar_dni_profesor_editado
    defaults: { _controller: "BackendBundle:Profesor:ComprobarDniProfesorEditado" }
    options:
        expose: true

profesores_por_curso:
    path:     /profesores_por_curso/{id}
    defaults: { _controller: "BackendBundle:Profesor:ProfesoresPorCurso" }
    options:
        expose: true

datos_profesor:
    path:     /datos_profesor/{id}
    defaults: { _controller: "BackendBundle:Profesor:DatosProfesor" }
    options:
        expose: true

datos_antiguo_profesor:
    path:     /datos_antiguo_profesor/{id}
    defaults: { _controller: "BackendBundle:Profesor:DatosAntiguoProfesor" }
    options:
        expose: true

search_old_teacher:
    path:     /profesor/old/search
    defaults: { _controller: "BackendBundle:Profesor:SearchOld" }
    options:
        expose: true

baja_profesor:
    path:     /profesor/baja
    defaults: { _controller: "BackendBundle:Profesor:BajaProfesor" }
    options:
        expose: true

alta_profesor:
    path:     /profesor/alta
    defaults: { _controller: "BackendBundle:Profesor:AltaProfesor" }
    options:
        expose: true

clases_impartidas:
    path:     /clases_impartidas
    defaults: { _controller: "BackendBundle:Profesor:ClasesImpartidas" }
    options:
        expose: true

horario_profesor:
    pattern:  /{id}/horario
    defaults: { _controller: "BackendBundle:Profesor:HorarioDelProfesor"}
    options:
      expose: true

horario_profesor_pdf:
    pattern:  /{id}/horarioPdf
    defaults: { _controller: "BackendBundle:Profesor:HorarioDelProfesorPdf", _format: pdf}
    options:
      expose: true

restablecer_contraseña_profesor:
    pattern:  /restablecer_password/{id}
    defaults: { _controller: "BackendBundle:Profesor:RestablecerPassword"}
    options:
      expose: true