profesor:
    path:     /
    defaults: { _controller: "BackendBundle:Profesor:index" }

profesor_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Profesor:show" }

profesor_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Profesor:new" }

profesor_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Profesor:create" }
    requirements: { _method: post }

profesor_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Profesor:edit" }

profesor_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Profesor:update" }
    requirements: { _method: post|put }

profesor_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Profesor:delete" }
    requirements: { _method: post|delete }
