reserva:
    path:     /consultar/{tipo}
    defaults: { _controller: "BackendBundle:Reserva:index" }

reserva_instalaciones:
    path:     /instalaciones
    defaults: { _controller: "BackendBundle:Reserva:instalaciones" }

reserva_equipamientos:
    path:     /equipamientos
    defaults: { _controller: "BackendBundle:Reserva:equipamientos" }

comprobar_reserva:
    path:     /comprobar_reservas
    defaults: { _controller: "BackendBundle:Reserva:ComprobarReservas" }
    options:
        expose: true

equipamiento_reservado:
    path:     /equipamiento_reservado
    defaults: { _controller: "BackendBundle:Reserva:EquipamientoReservado" }
    options:
        expose: true

reserva_show:
    path:     /{id}/show
    defaults: { _controller: "BackendBundle:Reserva:show" }

reserva_new:
    path:     /new
    defaults: { _controller: "BackendBundle:Reserva:new" }

reserva_create:
    path:     /create
    defaults: { _controller: "BackendBundle:Reserva:create" }
    requirements: { _method: post }
    options:
        expose: true

reserva_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackendBundle:Reserva:edit" }

reserva_update:
    path:     /{id}/update
    defaults: { _controller: "BackendBundle:Reserva:update" }
    requirements: { _method: post|put }

reserva_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackendBundle:Reserva:delete" }
    requirements: { _method: post|delete }
    options:
        expose: true

obtener_reserva:
    path:     /obtener_reserva
    defaults: { _controller: "BackendBundle:Reserva:ObtenerReserva" }
    options:
        expose: true