<?php

namespace Cole\IntranetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AusenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AusenciaRepository extends EntityRepository
{
	public function findFaltasClase($grupo, $asignatura, $fecha, $horario)
	{
		return $this->getEntityManager()->createQuery(
			'SELECT a FROM IntranetBundle:Ausencia a INNER JOIN a.alumno alum WHERE alum.grupo=:grupo AND a.asignatura=:asignatura  
			AND a.fecha=:fecha AND a.horario=:horario ORDER BY a.fecha ASC')
			->setParameters(array(
			'grupo' => $grupo,
			'asignatura' => $asignatura,
			'fecha' => $fecha,
			'horario' => $horario))
			->getResult();
	}

}
