<?php

namespace Cole\IntranetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AvisosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisosRepository extends EntityRepository
{

	public function findAvisosAlumno($alumno, $tipoUsuario, $tipoAviso)
	{
		return $this->getEntityManager()->createQuery(
		'SELECT a FROM IntranetBundle:Avisos a WHERE a.idUsuario=:alumno AND a.tipoUsuario=:tipoUsuario AND a.tipoAviso=:tipoAviso ORDER BY a.id ASC')
		->setParameters(array(
		'alumno' => $alumno,
		'tipoUsuario'=>$tipoUsuario,
		'tipoAviso'=>$tipoAviso))
		->getResult();
	}


	public function findExistenciaAviso($idUsuario, $tipoUsuario , $idAviso, $tipoAviso)
	{
		return $this->getEntityManager()->createQuery(
		'SELECT a FROM IntranetBundle:Avisos a WHERE a.idUsuario=:idUsuario AND a.tipoUsuario=:tipoUsuario AND a.tipoAviso=:tipoAviso AND a.idAviso=:idAviso ORDER BY a.id ASC')
		->setParameters(array(
		'idUsuario' => $idUsuario,
		'idAviso'=>$idAviso,
		'tipoUsuario'=>$tipoUsuario,
		'tipoAviso'=>$tipoAviso))
		->getResult();
	}

	public function findseguimientoLeido($idUsuario, $idAviso)
	{
		return $this->getEntityManager()->createQuery(
		'SELECT a FROM IntranetBundle:Avisos a WHERE a.idUsuario=:idUsuario AND a.tipoUsuario=:tipoUsuario AND a.tipoAviso=:tipoAviso AND a.idAviso=:idAviso')
		->setParameters(array(
		'idUsuario' => $idUsuario,
		'idAviso'=>$idAviso,
		'tipoUsuario'=>"Alumno",
		'tipoAviso'=>"Seguimiento"))
		->setMaxResults(1)
		->getOneOrNullResult();
	}

	public function findseguimientoConsultado($idAviso,$idUsuario,$tipoUsuario)
	{
		return $this->getEntityManager()->createQuery(
		'SELECT a FROM IntranetBundle:Avisos a WHERE a.idUsuario=:idUsuario AND a.tipoUsuario=:tipoUsuario AND a.tipoAviso=:tipoAviso AND a.idAviso=:idAviso')
		->setParameters(array(
		'idUsuario' => $idUsuario,
		'idAviso'=>$idAviso,
		'tipoUsuario'=>$tipoUsuario,
		'tipoAviso'=>"Seguimiento"))
		->setMaxResults(1)
		->getOneOrNullResult();
	}


}
