<?php

namespace Cole\IntranetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TareaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TareaRepository extends EntityRepository
{

		public function findTareaByProfesorGrupo($tarea, $profesor, $grupo)
	{
		return $this->getEntityManager()->createQuery(
			'SELECT t FROM IntranetBundle:Tarea t WHERE t.descripcion=:tarea AND t.profesor=:profesor AND t.grupo=:grupo')
			->setParameters(array(
			'tarea' => $tarea,
			'profesor' => $profesor,
			'grupo' => $grupo))
			->setMaxResults(1)
			->getOneOrNullResult();
	}

	public function findTareasComunes($profesor)
	{
		return $this->getEntityManager()->createQuery(
			'SELECT t FROM IntranetBundle:Tarea t WHERE t.profesor=:profesor GROUP BY t.asignatura, t.descripcion ORDER BY t.fecha DESC')
			->setParameters(array(
			'profesor' => $profesor))
			->getResult();
	}

	public function findByDescripcionOrdenado($tarea, $asignatura)
	{
		return $this->getEntityManager()->createQuery(
			'SELECT t FROM IntranetBundle:Tarea t INNER JOIN t.grupo g INNER JOIN g.curso c WHERE t.descripcion=:tarea AND t.asignatura=:asignatura  ORDER BY c.curso, g.letra ASC')
			->setParameters(array(
			'asignatura' => $asignatura,
			'tarea' => $tarea))
			->getResult();
	}

	public function findUltimaTarea($profesor)
	{
		return $this->getEntityManager()->createQuery(
			'SELECT t FROM IntranetBundle:Tarea t WHERE t.profesor=:profesor ORDER BY t.fecha DESC')
		->setParameters(array(
			'profesor' => $profesor))
		->setMaxResults(1)
		->getSingleResult();
	}

}
