<?php

namespace Cole\IntranetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TutoriasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TutoriasRepository extends EntityRepository
{
	
	public function findTutoriasPendientesProfesor($profesor)
	{

		return $this->getEntityManager()->createQuery(
			'SELECT t FROM IntranetBundle:Tutorias t WHERE t.profesor=:profesor AND t.activo=:activo AND t.fecha>= CURRENT_DATE()
			AND t.profesor IS NOT NULL AND t.alumno IS NOT NULL AND t.responsable IS NOT NULL ORDER BY t.fecha ASC')
			->setParameters(array(
			'profesor' => $profesor,
			'activo'=>1))
			->getResult();
	}

	public function findTutoriasPendientesAlumno($alumno, $responsable)
	{

		return $this->getEntityManager()->createQuery(
			'SELECT t FROM IntranetBundle:Tutorias t WHERE t.alumno=:alumno AND t.responsable=:responsable AND t.activo=:activo AND t.fecha>= CURRENT_DATE()
			AND t.profesor IS NOT NULL AND t.alumno IS NOT NULL AND t.responsable IS NOT NULL ORDER BY t.fecha ASC')
			->setParameters(array(
			'alumno' => $alumno,
			'responsable' => $responsable,
			'activo'=>1))
			->getResult();
	}
	//Consulta para obtener la tutoria de una consulta, ya sea confirmada (activo=1) o pendiente de confirmar (activo=0)
	public function findTutoriaConsulta($num)
	{
		return $this->getEntityManager()->createQuery(
			'SELECT t FROM IntranetBundle:Tutorias t WHERE t.seguimiento=:seguimiento')
			->setParameters(array(
			'seguimiento' => $num))
			->setMaxResults(1)
			->getOneOrNullResult();
	}


}
