intranet:
    path:     /intranet
    defaults: { _controller: IntranetBundle:Default:index }

intranet_perfil:
    path:     /intranet/perfil
    defaults: { _controller: IntranetBundle:Default:perfil}

intranet_alumno:
    path:     /intranet/alumno/{id}
    defaults: { _controller: IntranetBundle:Alumno:index }