intranet:
    path:     /intranet
    defaults: { _controller: IntranetBundle:Default:index }
    options:
        expose: true

intranet_perfil:
    path:     /intranet/perfil
    defaults: { _controller: IntranetBundle:Default:perfil}
    options:
        expose: true

actualizar_password:
    path:     /intranet/actualizar_password/{id}
    defaults: { _controller: IntranetBundle:Default:ActualizarPassword}
    options:
        expose: true
    requirements: { _method: post|put|get }

datos_personales_alumno:
    path:     /intranet/datos_personales_alumno/{id}
    defaults: { _controller: IntranetBundle:Alumno:DatosPersonales}
    options:
        expose: true
    requirements: { _method: post|put|get }

datos_personales:
    path:     /intranet/datos_personales/{id}
    defaults: { _controller: IntranetBundle:Default:DatosPersonales}
    options:
        expose: true
    requirements: { _method: post|put|get }

IntranetBundle_alumnos:
    resource: "@IntranetBundle/Resources/config/routing/alumnos.yml"
    prefix:   /intranet/alumno/{id}
