intranet:
    path:     /intranet
    defaults: { _controller: IntranetBundle:Default:index }
    options:
        expose: true

intranet_perfil:
    path:     /intranet/perfil
    defaults: { _controller: IntranetBundle:Default:perfil}
    options:
        expose: true

actualizar_password:
    path:     /intranet/actualizar_password/{id}
    defaults: { _controller: IntranetBundle:Default:ActualizarPassword}
    options:
        expose: true
    requirements: { _method: post|put|get }

datos_personales_alumno:
    path:     /intranet/datos_personales_alumno/{id}
    defaults: { _controller: IntranetBundle:Alumno:DatosPersonales}
    options:
        expose: true
    requirements: { _method: post|put|get }

intranet_alumno:
    path:     /intranet/alumno/{id}
    defaults: { _controller: IntranetBundle:Alumno:index}

intranet_alumno_perfil:
    path:     /intranet/alumno/{id}/perfil
    defaults: { _controller: IntranetBundle:Alumno:perfil}


datos_personales:
    path:     /intranet/datos_personales/{id}
    defaults: { _controller: IntranetBundle:Default:DatosPersonales}
    options:
        expose: true
    requirements: { _method: post|put|get }

intranet_alumno_curso:
    path:     /intranet/alumno/{id}/curso
    defaults: { _controller: IntranetBundle:Alumno:curso}

horario_alumno:
    pattern:  /intranet/alumno/{id}/horario
    defaults: { _controller: "IntranetBundle:Alumno:Horario"}
    options:
      expose: true

horario_alumno_pdf:
    pattern:  /intranet/alumno/{id}/horarioPdf
    defaults: { _controller: "IntranetBundle:Alumno:HorarioPdf", _format: pdf}
    options:
      expose: true

intranet_alumno_noticias:
    path:     /intranet/alumno/{id}/noticias
    defaults: { _controller: IntranetBundle:Alumno:noticias}

intranet_alumno_noticia:
    path:     /intranet/alumno/{id}/noticia/{num}
    defaults: { _controller: IntranetBundle:Alumno:noticia}