parameters:
#    intranet.example.class: Cole\IntranetBundle\Example

services:
#    intranet.example:
#        class: %intranet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
