<?php

namespace Cole\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdministrativoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministrativoRepository extends EntityRepository
{

	public function findAdminActivo()
	{
	return $this->getEntityManager()->createQuery(
		'SELECT a FROM BackendBundle:Administrativo a WHERE a.fechaBaja IS NULL ORDER BY a.apellido1, a.apellido2, a.nombre')
		->getResult();
	}

	public function findAdminInactivo()
	{
	return $this->getEntityManager()->createQuery(
		'SELECT a FROM BackendBundle:Administrativo a WHERE a.fechaBaja IS NOT NULL ORDER BY a.apellido1, a.apellido2, a.nombre')
		->getResult();
	}

}
