<?php

namespace Cole\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AsignaturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignaturaRepository extends EntityRepository
{
	public function findNumAsignaturas()
	{
	return $this->getEntityManager()->createQuery(
		'SELECT	COUNT(a) FROM BackendBundle:Asignatura a ')
		->setMaxResults(1)
		->getOneOrNullResult();
	}
}
