<?php

namespace Cole\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AsignaturasCursosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignaturasCursosRepository extends EntityRepository
{

	public function findAsignaturasCursos($id)
	{
	return $this->getEntityManager()->createQuery(
		'SELECT a FROM BackendBundle:AsignaturasCursos a INNER JOIN a.curso c INNER JOIN a.asignatura asig WHERE c.id=:id ORDER BY  asig.tipo DESC,asig.nombre')
		->setParameters(array(
			'id' => $id))
		->getResult();
	}
	
	public function findAsignaturasTroncalesCurso($id)
	{
	return $this->getEntityManager()->createQuery(
		'SELECT a FROM BackendBundle:AsignaturasCursos a INNER JOIN a.curso c INNER JOIN a.asignatura asig WHERE c.id=:id and asig.tipo=:tipo ORDER BY  asig.tipo DESC,asig.nombre')
		->setParameters(array(
			'id' => $id,
			'tipo' => "Troncal"))
		->getResult();
	}

	public function findAsignaturasEspecificasCurso($id)
	{
	return $this->getEntityManager()->createQuery(
		'SELECT a FROM BackendBundle:AsignaturasCursos a INNER JOIN a.curso c INNER JOIN a.asignatura asig WHERE c.id=:id and asig.tipo=:tipo ORDER BY  asig.tipo DESC,asig.nombre')
		->setParameters(array(
			'id' => $id,
			'tipo' => "Específica"))
		->getResult();
	}

	public function findAsignacion($curso, $asig){

	return $this->getEntityManager()->createQuery(
		'SELECT a FROM BackendBundle:AsignaturasCursos a INNER JOIN a.curso c INNER JOIN a.asignatura asig WHERE c.id=:id and asig.id=:asig')
		->setParameters(array(
			'id' => $curso,
			'asig' => $asig))
		->setMaxResults(1)
		->getOneOrNullResult();
	}
	

}
