<?php

namespace Cole\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AsignaturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignaturaRepository extends EntityRepository
{
	public function findNumAsignaturas()
	{
	return $this->getEntityManager()->createQuery(
		'SELECT	COUNT(a) FROM BackendBundle:Asignatura a ')
		->setMaxResults(1)
		->getOneOrNullResult();
	}

	public function findByNombreEdit($nombre,$id)
	{
	return $this->getEntityManager()->createQuery(
		'SELECT	a FROM BackendBundle:Asignatura a where a.nombre=:nombre and a.id NOT IN (:id)')
		->setParameters(array(
			'id' => $id,
			'nombre' => $nombre))
		->setMaxResults(1)
		->getOneOrNullResult();
	}

	public function findByOpcionalEdit($id)
	{
	return $this->getEntityManager()->createQuery(
		'SELECT	a FROM BackendBundle:Asignatura a where a.opcional=:opcional and a.id NOT IN (:id)')
		->setParameters(array(
			'id' => $id,
			'opcional' => 1))
		->getResult();
	}
}
