<?php

namespace Cole\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AsignaturasCursosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignaturasCursosRepository extends EntityRepository
{

	public function findAsignaturasCursos($id)
	{
	return $this->getEntityManager()->createQuery(
		'SELECT a FROM BackendBundle:AsignaturasCursos a INNER JOIN a.curso c INNER JOIN a.asignatura asig WHERE c.id=:id ORDER BY asig.opcional,asig.tipo DESC,asig.nombre')
		->setParameters(array(
			'id' => $id))
		->getResult();
	}
	
	public function findAsignaturasTroncalesCurso($id)
	{
	return $this->getEntityManager()->createQuery(
		'SELECT a FROM BackendBundle:AsignaturasCursos a INNER JOIN a.curso c INNER JOIN a.asignatura asig WHERE c.id=:id and asig.tipo=:tipo ORDER BY  asig.tipo DESC,asig.nombre')
		->setParameters(array(
			'id' => $id,
			'tipo' => "Troncal"))
		->getResult();
	}

	public function findAsignaturasEspecificasCurso($id)
	{
	return $this->getEntityManager()->createQuery(
		'SELECT a FROM BackendBundle:AsignaturasCursos a INNER JOIN a.curso c INNER JOIN a.asignatura asig WHERE c.id=:id and asig.tipo=:tipo ORDER BY  asig.tipo DESC,asig.nombre')
		->setParameters(array(
			'id' => $id,
			'tipo' => "Específica"))
		->getResult();
	}

	public function findAsignaturasEspecificasNoOpcionalesCurso($id)
	{
	return $this->getEntityManager()->createQuery(
		'SELECT a FROM BackendBundle:AsignaturasCursos a INNER JOIN a.curso c INNER JOIN a.asignatura asig WHERE c.id=:id and asig.tipo=:tipo and asig.opcional=:opcional ORDER BY  asig.tipo DESC,asig.nombre')
		->setParameters(array(
			'id' => $id,
			'opcional' => 0,
			'tipo' => "Específica"))
		->getResult();
	}

	public function findAsignaturasEspecificasOpcionalesCurso($id)
	{
	return $this->getEntityManager()->createQuery(
		'SELECT a FROM BackendBundle:AsignaturasCursos a INNER JOIN a.curso c INNER JOIN a.asignatura asig WHERE c.id=:id and asig.tipo=:tipo and asig.opcional=:opcional ORDER BY  asig.tipo DESC,asig.nombre')
		->setParameters(array(
			'id' => $id,
			'opcional' => 1,
			'tipo' => "Específica"))
		->getResult();
	}

	public function findAsignacion($curso, $asig){

	return $this->getEntityManager()->createQuery(
		'SELECT a FROM BackendBundle:AsignaturasCursos a INNER JOIN a.curso c INNER JOIN a.asignatura asig WHERE c.id=:id and asig.id=:asig')
		->setParameters(array(
			'id' => $curso,
			'asig' => $asig))
		->setMaxResults(1)
		->getOneOrNullResult();
	}

	public function findAsignacionNombre($curso, $nombre_asig){

	return $this->getEntityManager()->createQuery(
		'SELECT a FROM BackendBundle:AsignaturasCursos a INNER JOIN a.curso c INNER JOIN a.asignatura asig WHERE c.id=:id and asig.nombre=:asig')
		->setParameters(array(
			'id' => $curso,
			'asig' => $nombre_asig))
		->setMaxResults(1)
		->getOneOrNullResult();
	}

	public function findAsignaturasAlumno($curso, $optativa)
	{
	return $this->getEntityManager()->createQuery(
		'SELECT a FROM BackendBundle:AsignaturasCursos a INNER JOIN a.curso c INNER JOIN a.asignatura asig WHERE a.curso=:curso AND (asig.opcional=0 OR (asig.opcional=1 AND a.id=:optativa)) AND asig.nombre not like :asignatura  ORDER BY  asig.tipo DESC,asig.nombre')
		->setParameters(array(
			'curso' => $curso,
			'optativa' => $optativa,
			'asignatura' => "Tutoría"))
		->getResult();
	}


}
