<?php

namespace Cole\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventosRepository extends EntityRepository
{
	public function findEventosGenerales($categoria)
	{
	return $this->getEntityManager()->createQuery(
		"SELECT CONCAT(CONCAT(e.title, ' | '), e.hora) AS title, e.description, e.datetime FROM BackendBundle:Eventos e WHERE e.categoria=:categoria ORDER BY e.datetime ASC, e.hora ASC")
		->setParameters(array(
			'categoria' => $categoria))
		->getResult(\Doctrine\ORM\Query::HYDRATE_ARRAY);
	}

	public function findEventosPendientes()
	{
	return $this->getEntityManager()->createQuery(
		"SELECT e FROM BackendBundle:Eventos e WHERE e.datetime>=CURRENT_DATE() ORDER BY e.datetime ASC, e.hora ASC")
		->getResult();
	}

}
