<?php

namespace Cole\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExpedienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpedienteRepository extends EntityRepository
{

	public function findPorAño($id,$year)
	{
	return $this->getEntityManager()->createQuery(
		'SELECT e FROM BackendBundle:Expediente e WHERE e.alumno=:alumno AND e.anyo_Academico=:year')
		->setParameters(array(
			'alumno' => $id,
			'year'=>$year))
		->setMaxResults(1)
		->getOneOrNullResult();
	}

	public function findByActivo($curso,$nivel)
	{
        if(date("n")>=6){
            $actual=date("Y")." / ".(date("Y")+1);
        }
        else{
            $actual=(date("Y")-1)." / ".date("Y");
        }
	return $this->getEntityManager()->createQuery(
			'SELECT e,a FROM BackendBundle:Expediente e INNER JOIN e.alumno a INNER JOIN a.curso c WHERE a.activo=1  and e.curso=c.curso  and e.nivel=c.nivel and e.anyo_Academico=a.anyoAcademico and NOT(e.curso=:curso and e.nivel=:nivel and e.promociona=1) and Not e.anyo_Academico=:actual')
		->setParameters(array(
			'actual' => $actual,
			'curso' => $curso,
			'nivel' => $nivel))
		->getResult();
	}

	public function findNoActivos($curso,$nivel)
	{

	return $this->getEntityManager()->createQuery(
			'SELECT a,e FROM BackendBundle:Expediente e INNER JOIN e.alumno a  WHERE a.activo=0  and NOT(e.curso=:curso and e.nivel=:nivel and e.promociona=1)')
		->setParameters(array(
			'curso' => $curso,
			'nivel' => $nivel))
		->getResult();
	}
}

	
