<?php

namespace Cole\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FestivosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FestivosRepository extends EntityRepository
{

	public function findFestivosPorTipo($id)
	{
	return $this->getEntityManager()->createQuery(
		'SELECT f FROM BackendBundle:Festivos f WHERE f.tipo=:tipo ORDER BY f.numMes, f.dia ')
		->setParameters(array(
			'tipo' => $id))
		->getResult();
	}

	public function findFestivosPorMes($id)
	{
	return $this->getEntityManager()->createQuery(
		'SELECT f FROM BackendBundle:Festivos f WHERE f.numMes=:mes ORDER BY f.numMes, f.dia ')
		->setParameters(array(
			'mes' => $id))
		->getResult();
	}

	public function findFestivosPorDescripcion($data)
	{
		return $this->getEntityManager()->createQuery(
			'SELECT f FROM BackendBundle:Festivos f WHERE f.descripcion=:data')
		->setParameters(array(
			'data' => $data))
		->setMaxResults(1)
		->getOneOrNullResult();
	}


	public function findFestivo($dia, $mes)
	{
		return $this->getEntityManager()->createQuery(
			'SELECT f FROM BackendBundle:Festivos f WHERE f.dia=:dia AND f.numMes=:mes')
		->setParameters(array(
			'dia' => $dia,
			'mes' => $mes))
		->setMaxResults(1)
		->getOneOrNullResult();
	}

	public function findDiasFestivos($mes)
	{
		return $this->getEntityManager()->createQuery(
			'SELECT f.dia FROM BackendBundle:Festivos f WHERE f.numMes=:mes ORDER BY f.dia ')
		->setParameters(array(
			'mes' => $mes))
		->getResult();
	}

	public function findDiaVacaciones($mes,$descripcion)
	{
		return $this->getEntityManager()->createQuery(
			'SELECT f.dia FROM BackendBundle:Festivos f WHERE f.numMes=:mes and f.descripcion like :descripcion  ORDER BY f.dia ')
		->setParameters(array(
			'mes' => $mes,
			'descripcion' => $descripcion."%"))
		->setMaxResults(1)
		->getOneOrNullResult();
	}



}
