<?php

namespace Cole\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GrupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoRepository extends EntityRepository
{
	public function findGrupoByLetter($curso,$letra)
	{
		return $this->getEntityManager()->createQuery(
			'SELECT g FROM BackendBundle:Grupo g WHERE g.curso=:curso AND g.letra=:letra')
		->setParameters(array(
			'curso' => $curso,
			'letra' => $letra))
		->setMaxResults(1)
		->getOneOrNullResult();
	}
	public function findGruposByCurso($curso)
	{
		return $this->getEntityManager()->createQuery(
		'SELECT g FROM BackendBundle:Grupo g WHERE g.curso=:curso ORDER BY g.letra')
		->setParameters(array(
			'curso' => $curso))
		->getResult();
	}

	public function findGruposByNivel($nivel)
	{
		return $this->getEntityManager()->createQuery(
		'SELECT g FROM BackendBundle:Grupo g INNER JOIN g.curso c WHERE c.nivel=:nivel ORDER BY c.numOrden, g.letra')
		->setParameters(array(
			'nivel' => $nivel))
		->getResult();
	}

	public function findAllByCurso()
	{
		return $this->getEntityManager()->createQuery(
		'SELECT g,c FROM BackendBundle:Grupo g INNER JOIN g.curso c ORDER BY c.numOrden, g.letra')
		->getResult();
	}
		public function findPrimariaByCurso()
	{
		return $this->getEntityManager()->createQuery(
		'SELECT g FROM BackendBundle:Grupo g INNER JOIN g.curso  c WHERE c.nivel=:nivel ORDER BY c.numOrden, g.letra')
		->setParameters(array(
			'nivel' => "Primaria"))
		->getResult();
	}


}
