<?php

namespace Cole\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HorarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorarioRepository extends EntityRepository
{
	public function findAllOrdenado()
	{
		return $this->getEntityManager()->createQuery(
		'SELECT h FROM BackendBundle:Horario h ORDER BY h.id ASC')
		->getResult();
	}

	public function findHoraClase($clase)
	{
		return $this->getEntityManager()->createQuery(
		'SELECT h FROM BackendBundle:Horario h WHERE h.horaClase=:horaClase')
		->setParameters(array(
			'horaClase' => $clase))
		->setMaxResults(1)
		->getOneOrNullResult();
	}

	public function findOneByHora($ini, $fin)
	{
		return $this->getEntityManager()->createQuery(
		'SELECT h FROM BackendBundle:Horario h WHERE h.inicio=:inicio and h.fin=:fin ')
		->setParameters(array(
			'inicio' => $ini,
			'fin' => $fin))
		->setMaxResults(1)
		->getOneOrNullResult();
	}

	public function findClases()
	{
		return $this->getEntityManager()->createQuery(
		'SELECT h FROM BackendBundle:Horario h WHERE h.horaClase not like :recreo 
		and h.horaClase not like :comida')
		->setParameters(array(
			'recreo' => "RECREO",
			'comida' => "COMIDA"))
		->getResult();
	}

	public function findDuracionHorarioAutomatico()
	{
		return $this->getEntityManager()->createQuery(
		'SELECT h FROM BackendBundle:Horario h')
		->setMaxResults(1)
		->getOneOrNullResult();
	}
	
	public function findByHora($hora)
	{
		return $this->getEntityManager()->createQuery(
		'SELECT h FROM BackendBundle:Horario h WHERE h.inicio<=:hora and h.fin>=:hora')
		->setParameters(array(
			'hora' => $hora))
		->setMaxResults(1)
		->getOneOrNullResult();
	}
	

}
