<?php

namespace Cole\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImparteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImparteRepository extends EntityRepository
{

		public function findByCurso($curso)
	{
		return $this->getEntityManager()->createQuery(
		'SELECT i FROM BackendBundle:Imparte i WHERE i.curso=:curso')
		->setParameters(array(
			'curso' => $curso))
		->getResult();
	}



}
